Repository Telnaior/RtaB-Bot, pull requests merged in 2018-07, with the labels that each got.

#1 Feature - New Minigame (The Offer)
  src/tel/discord/rtab/enums/Games.java
  src/tel/discord/rtab/minigames/TheOffer.java
Labels: enhancement

#2 Deuces wild
  src/tel/discord/rtab/enums/CardRank.java
  src/tel/discord/rtab/enums/CardSuit.java
  src/tel/discord/rtab/enums/Games.java
  src/tel/discord/rtab/enums/PokerHand.java
  src/tel/discord/rtab/minigames/DeucesWild.java
  src/tel/discord/rtab/objs/Card.java
  src/tel/discord/rtab/objs/Deck.java
Labels: enhancement

#5 Widens the board for large games
  src/tel/discord/rtab/GameController.java
Labels: enhancement

#6 Fixed "wasted space already picked" bug
  src/tel/discord/rtab/GameController.java
Labels: bug

#7 Fixed header for wide boards
  src/tel/discord/rtab/GameController.java
Labels: bug

#8 Create DoubleTrouble.java
  src/tel/discord/rtab/minigames/DoubleTrouble.java
Labels: enhancement

#9 Cleaned up DoubleTrouble
  src/tel/discord/rtab/enums/Games.java
  src/tel/discord/rtab/minigames/DoubleTrouble.java
Labels: bug

#12 Expanded Bot-Adding Functionality
  src/tel/discord/rtab/GameController.java
  src/tel/discord/rtab/RaceToABillionBot.java
  src/tel/discord/rtab/commands/AddBotCommand.java
  src/tel/discord/rtab/commands/DemoCommand.java
Labels: enhancement

#14 THE NERFHAMMER STRIKES AGAIN
  src/tel/discord/rtab/minigames/DoubleTrouble.java
Labels: rebalance

#16 Shuffle Order
  src/tel/discord/rtab/GameController.java
  src/tel/discord/rtab/enums/Events.java
Labels: enhancement

#21 Deuces wild bugfixes
  src/tel/discord/rtab/minigames/DeucesWild.java
Labels: bug
