Repository Telnaior/RtaB-Bot, pull requests merged in 2018-09, with the labels that each got.

#27 Removed garbage from CodeBlocks
  src/tel/discord/rtab/minigames/TheOffer.java
Labels: bug

#28 Bumper Grab, pre-tweaking for balance and display prettiness
  src/tel/discord/rtab/enums/Games.java
  src/tel/discord/rtab/minigames/BumperGrab.scala
  src/tel/discord/rtab/minigames/MinigameTest.scala
Labels: enhancement, season 2

#29 Bumper cash
  src/tel/discord/rtab/minigames/BumperGrab.scala
Labels: clarify, season 2

#30 Create DoubleZeroes.java
  src/tel/discord/rtab/minigames/DoubleZeroes.java
Labels: enhancement, season 2
